package br.com.filipe.conferidor_relatorios.model;
public enum Cenario {
    VALIDO_COM_TARIFA, VALIDO_SEM_TARIFA, INVALIDADO_AUTO, INVALIDADO_COM_TARIFA, INVALIDADO_SEM_TARIFA,
    MKP_LOCAL, MKP_REMOTO, SILCE, DISPONIVEIS, MKP_INVALIDADO_OUTRA_TFL, MKP_INVALIDADO_NA_TFL, MKP_GERADO_INVALIDADO_OUTRA_TFL;
}
